from pydantic import BaseModel, Field
from typing import List

class ChatRequest(BaseModel):
    message: str = Field(
        ..., 
        min_length=1, 
        max_length=1000, 
        description="The chat message input from the user."
    )

class ChatResponse(BaseModel):
    answer: str = Field(..., description="The response generated by the chatbot.")
    intent: str = Field(..., description="The classified intent of the user message.")
    confidence: float = Field(..., description="The confidence score of the intent/retrieval.")
    sources: List[str] = Field(default=[], description="List of knowledge base IDs used for the answer.")
